As a part of database initialization, create roles and set class level permissions
evandana/keep-ahope-gcp pull request #8
Opened 2019-01-19 17:13 UTC by pandathegiant

This PR includes the code in the back-end to do the following when the server starts up:

1. creates a few "built-in" roles (Viewer and Editor primarily) in Parse if they do not exist yet,
1. configures nested role membership, and
1. uses the roles to set class-level permissions on event and contacts classes.

2019-01-20 15:29 UTC, evandana requested changes
@pandathegiant Looks good! Two minor suggested changes.

@ahulab Can you review the functionality of this?

2019-01-20 15:29 UTC, evandana commented on parseSchema/index.js
> +  allPromises.push(promise);
#changerequested

In general, the pattern of adding promises to the `allPromises` array and then doing a `Promise.all()` is great. However, instead of mutating `promise`, how about creating a few differently named vars, like `const createAdminEditorWriterViewerPromise = `, such that the naming makes the `allPromises.push(descriptivePromiseName)` more clear?

2019-01-20 15:29 UTC, evandana commented on parseSchema/index.js
> +  return (new Parse.Query(Parse.Role))
#changerequested

So great to have your code comments here!

Can you ensure that the package.json files specifies the parse dependencies locked down (e.g. does NOT use `^` or `~` which would enable a variable patch/minor version change)?

2019-01-20 16:19 UTC, pandathegiant commented on parseSchema/index.js
> +  allPromises.push(promise);
Will do!

2019-01-20 16:20 UTC, pandathegiant commented on parseSchema/index.js
> +  return (new Parse.Query(Parse.Role))
okay, how about just committing package-lock.json? @evandana

2019-01-22 01:25 UTC, pandathegiant commented on parseSchema/index.js
> +  allPromises.push(promise);
Updated in the latest commit.

2019-01-29 01:00 UTC, evandana reviewed
This looks like a ton of work! Thanks for orchestrating such a fix!

A few questions about how well this might fare over 3 years, but otherwise looks good.

2019-01-29 01:00 UTC, evandana commented on post-deploy.sh
> +# Step #n: target url: [https://ahope-parse-poc.appspot.com]
Thanks for all these comments

2019-01-29 01:00 UTC, evandana commented on post-deploy.sh
> +sed -nr 's/^.*MK_SALT:[[:space:]]+"(.+)"/mk_salt=\1/p' app.standard.yaml  >> setup.sh
How robust are these scripts? How can we ensure they keep working for 3+ years?

Can this log that it's working (without logging the sensitive details)?

2019-01-29 01:10 UTC, evandana commented on parseSchema/index.js
> +  return (new Parse.Query(Parse.Role))
Yup, let's do that.

2019-01-29 02:29 UTC, pandathegiant commented on post-deploy.sh
> +sed -nr 's/^.*MK_SALT:[[:space:]]+"(.+)"/mk_salt=\1/p' app.standard.yaml  >> setup.sh
This shell script does rely on the fact that GCP cloud build's logging will print out version id (and the project id and the service name, to a lesser degree) in a given format.  But beyond that, everything is either under our control, or specifically documented by GCP (such as the format of version-specific service URL).  So I expect it continue to work.

Also this script only ensures the schema initialization code is called at the end of each build, which really matters only when the schema initialization code changes.  It probably isn't too much to ask for, to take a look at the log to confirm that schema initialization has succeeded.  In all other cases, the script can fail without consequences.

Yes, at the end of the log it does indicate if initialization is successful or not.  Here is an example (from https://console.cloud.google.com/cloud-build/builds/80f89e32-96c0-46bd-b864-ceedbddaecaa?project=ahope-parse-poc):

```
Step #6: --- ready to set up environment for triggering the db init. ---
Step #6: Sending init-db request to https://20190128t015627-dot-default-dot-ahope-parse-poc.appspot.com/parse/ahopeinit
Step #6: {"status":"ok"}
Step #6: Schema initialization completed.
Finished Step #6
```

Speaking of sensitive details - the logs are only viewable to who have logged into GCP console and who have been given permissions, so they should be considered safe.  Nonetheless we try not to log sensitive data unless it's necessary.

2019-01-31 02:10 UTC, pandathegiant commented on parseSchema/index.js
> +  return (new Parse.Query(Parse.Role))
Done... package-lock.json committed.

2019-01-31 04:33 UTC, ahulab reviewed
made some comments. feel free to ignore the stuff about removing 'ahope' wording from the source code. that's not a requirement, I just wanted to call it out. Otherwise this stuff looks pretty good. The log file parsing makes me kind of nervous, I have a tough time believing that we can't get that same info from a gcp api, but I couldn't find anything in my quick document search, so I'll take your word for it

2019-01-31 04:33 UTC, ahulab commented on cloudbuild.yaml
> +  args: ['ash', '-c', 'sed -i s#%%mk_salt_value%%#$(head -c 48 /dev/urandom | base64)# ./app.standard.yaml']
what's `ash` ?

2019-01-31 04:33 UTC, ahulab commented on server.js
> +  .catch(() => {
is it worth capturing the error message and logging it to the client here? this catch swallows the error message, could make debugging a little trickier if something goes wrong here

2019-01-31 04:33 UTC, ahulab commented on server.js
> +  if (process.env.MK_SALT) {
you know much more than I do about the gcp deployment at this point, so I apologize in advance if I'm thinking about this wrong.. but I think all non-reserved google cloud environment variables are mutable. so can we really 100% guarantee that this env var will be set at runtime? we also allow users to modify the yaml files, so they could potentially fudge with this value.

it does look like there are a set of reserved environment variables that google will set for you in all deployments, and the user cannot overwrite or delete them. `project` is one for example. (some more https://cloud.google.com/deployment-manager/docs/configuration/templates/use-environment-variables). 

since it looks like the purpose of this conditional statement is to determine whether or not we're running in the cloud, maybe it's wise to alter it like so:
```
(process.env.project && process.env.MK_SALT)
```

my main concern is that if MK_SALT is somehow unset at the time when this function runs, the entire authentication path will be skipped

2019-01-31 04:33 UTC, ahulab commented on package.json
> +  "name": "appengine-parse-server-for-bphc-ahope",
in the spirit of keeping this code from being totally tailored to the needs of one client (BPHC) I think we should keep all BPHC and AHOPE wording from entering the source code. This comment applies globally

2019-01-31 04:33 UTC, ahulab commented on server.js
> +app.post(PARSE_MOUNT_PATH + '/ahopeinit', function (req, res) {
how about calling this `/schema-init` or something non-ahope related?

2019-01-31 04:33 UTC, ahulab commented on server.js
>    if (!appSettings.appName) appSettings.appName = "AHOPE Administrators Dashboard";
how about using `process.env.PROJECT_ID` instead of `AHOPE` so that non ahope folks can use their own dashboard name in the future

2019-01-31 04:51 UTC, pandathegiant commented on cloudbuild.yaml
> +  args: ['ash', '-c', 'sed -i s#%%mk_salt_value%%#$(head -c 48 /dev/urandom | base64)# ./app.standard.yaml']
ash is the shell that comes with Busybox.  Pretend it is bash... :-)
[https://linux.die.net/man/1/ash](https://linux.die.net/man/1/ash)

2019-01-31 04:56 UTC, pandathegiant commented on server.js
> +  .catch(() => {
okay, any error should have been logged here:
https://github.com/evandana/keep-ahope-gcp/pull/8/files#diff-856c9942d7d8b144c262b3cf742d32edR244

Notice that that catch returns a rejected promise so this catch is executed and return a simple text to the REST client.

2019-01-31 05:09 UTC, pandathegiant commented on server.js
> +  if (process.env.MK_SALT) {
No apology needed and certainly good question. :-)

The short answer is that this environment variable is set in app.standard.yml file.  Short of someone altering that file or changing the javascript code here, we should be able to count on its presence.  In fact, this environment variable is how we pass the build-time generated random number to run-time for the purpose of generating a master key.

Even in the worst possible scenario that the auth path here were skipped, the attacker's only gain would be running schema initialization, which is idempotent.  So the service would be made less or not available, but the actual data stored in database would not be at risk.

2019-01-31 05:15 UTC, pandathegiant commented on package.json
> +  "name": "appengine-parse-server-for-bphc-ahope",
This is worth a discussion.  I hold no strong opinion and have no problem removing it.

2019-01-31 05:17 UTC, pandathegiant commented on server.js
>    if (!appSettings.appName) appSettings.appName = "AHOPE Administrators Dashboard";
process.env.PROJECT_ID is lower case and is probably less descriptive... it''s what appears in the URL to the left of .appspot.com.  If we want to make it client-agnostic, we can find some generic wording.

2019-01-31 05:33 UTC, pandathegiant commented
Yes, a GCP Build API-based approach would be preferred over log file parsing, to get the version id, and the service name.  However, as I noted in [the source code](https://github.com/evandana/keep-ahope-gcp/blob/88bcb30d34eea1403b77f9c5f867970688da9b8a/post-deploy.sh#L14), [gcloud tool](https://cloud.google.com/sdk/gcloud/reference/builds/describe) doesn't give us a way to retrieve the generated version id.  And the [REST API](https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds) is the same (plus the trouble to get an OAuth token).

If we cannot quickly decide on whether the ahope verbiage should be removed, I suggest that this PR be approved first and that a separate issue be created to remove ahope verbiage.

2019-02-01 03:00 UTC, ahulab approved these changes

2019-02-01 03:00 UTC, ahulab commented
I don't think we need to get the AHOPE wording out of here at the moment, let's just do that later and not block this PR any longer

2019-02-01 16:13 UTC, pandathegiant commented on server.js
> +app.post(PARSE_MOUNT_PATH + '/ahopeinit', function (req, res) {
will address separately per suggestion.

2019-02-01 16:14 UTC, pandathegiant commented
@evandana if you feel comfortable with the changes made in response to your comment, please approve.

2019-02-10 18:19 UTC, evandana approved these changes

2019-02-10 18:19 UTC, merged